# sops-nix configuration
# See: https://github.com/Mic92/sops-nix

# Setup instructions:
# 1. Admin key (your workstation):
#    age-keygen -o ~/.config/sops/age/keys.txt
#    age-keygen -y ~/.config/sops/age/keys.txt  # Get public key
#
# 2. Host keys (derive from SSH host key):
#    ssh root@<host> "cat /etc/ssh/ssh_host_ed25519_key.pub" | ssh-to-age
#    Add the resulting age public key to the hosts section below
#
# 3. Create/edit secrets:
#    sops secrets/secrets.yaml
#
# 4. Re-encrypt when adding new hosts:
#    sops updatekeys secrets/secrets.yaml

keys:
  # Admin keys (workstations that can encrypt/decrypt)
  - &admin age1jhxhe7w978fc4t6glav5pprtzdgy0juf8rqq4m7f6aelfmuz55fs7y5jdj

  # Host keys (derived from SSH host keys via ssh-to-age)
  # To get a host's age key: ssh-keyscan <host> 2>/dev/null | ssh-to-age
  # Or: ssh root@<host> "cat /etc/ssh/ssh_host_ed25519_key.pub" | ssh-to-age
  #
  # Example:
  # - &do-runner-1 age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  #
  # Uncomment and add your host keys here:
  - &do-runner-1 age1gg3m3t4zy943lqrdc8737mt5y8smzermmwpflu47y83hznjcva3qpmddzx
  - &nixtower age1jkn40dcwnlyly6lj8jwhl0k3sek65z8zfuelq2mtdkrjfgygje8q0j84wy

creation_rules:
  # Secrets encrypted for admin + all runner hosts
  # Only encrypt keys matching the pattern (keeps structure readable)
  - path_regex: secrets\.yaml$
    encrypted_regex: "^(gitlab_.*|gitea_.*|github_app_id|github_app_private_key|.*_secret|.*_password|.*_token|.*_key)$"
    key_groups:
      - age:
          - *admin
          # Add host keys here as you provision them:
          - *do-runner-1
          - *nixtower
